project:
  type: website
  output-dir: docs

resources:
  - CNAME
  
execute:
  freeze: auto

website:
  title: "Bruno Mioto"
  site-url: "https://brunomioto.com/"
  favicon: /figures/eye_website.png
  google-analytics: "G-XTWGVVSED5"
  description: "Hello, this is my personal website!"
  image: figures/header.png
  open-graph:
    description: "Hello, this is my personal website!"
    image: figures/header.png
  twitter-card:
    title: "Bruno Mioto"
    description: "Hello, this is my personal website!"
    creator: "@BrunoHMioto"
    card-style: summary_large_image
    image: figures/header.png

  navbar:
    logo: figures/eye_website.png
    foreground: "#40609f"
    background: "#f1f1f1"
    right:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Charts"
        file: charts.qmd
      - text: "R"
        menu:
          - text: "R packages"
            icon: "box-seam"
            href: r-packages.qmd
          - text: "Scripts"
            icon: "braces"
            href: scripts.qmd
          - text: "Twitter bots"
            icon: "robot"
            href: twitter-bots.qmd
      - text: "About me"
        file: about-en.qmd
  
  page-footer: 
    left: "Website made with Quarto by Bruno Mioto, 2025." 
    right: 
      - icon: github
        href: https://github.com/brunomioto
      - icon: twitter 
        href: https://twitter.com/BrunoHMioto

format:
  html:
    theme: 
      - united
      - styles.css
    toc: true

editor: source
