project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Bruno Mioto"
  favicon: /figures/logo.png
  navbar:
    logo: "figures/logo.png"
    foreground: "#40609f"
    background: "#f1f1f1"
    right:
      - href: index.qmd
        text: Home
      - charts.qmd
      - r-packages.qmd
      - about-en.qmd
  page-footer: 
    left: "Website made with [Quarto](https://quarto.org/) by Bruno Mioto, 2022" 
    right: 
      - icon: github
        href: https://github.com/brunomioto
      - icon: twitter 
        href: https://twitter.com/BrunoHMioto

  
format:
  html:
    theme:
      light: cosmo
      #dark: [cosmo, theme-dark.scss]
    toc: true

editor: visual

